.\" x-roff document
.do mso man.tmac
.TH tisp 1 "March 2018" "tisp 0.0.0"
.PP
.SH NAME
tisp - tiny lisp
.PP
.SH SYNOPSIS
\fBtisp\fP [\fB-hv\fP] [\fIFILENAME\fP] 
.PP
.SH DESCRIPTION
Tiny lisp implementation, still in heavy development, barely even "useable." Designed to be scheme-like, ie very minimalist.
.PP
.SH OPTIONS
.TP
\fB-h
\fRPrint help and exit
.PP
.TP
\fB-v
\fRPrint version info and exit
.PP
.SH USAGE
Run the program from the command line to launch the REPL, type a command and press enter to see the result.
.PP
.RS 4
.EX

$ tisp
> (+ (+ 1 2) 3)
6
> (+ 1 2 3)
6

.EE
.RE
.PP
Alternatively you can pass a file name which will be opened and run, outputting the result before exiting.
.PP
.RS 4
.EX

$ echo '(+ 1 2 3)' > add.lisp
$ tisp add.lisp
6

.EE
.RE
.PP
Commands can also be piped directing into tisp through the command line.
.PP
.RS 4
.EX

$ echo '(+ 1 2 3)' | tisp
6

.EE
.RE
.PP
.SH AUTHOR
Ed van Bruggen <edvb@uw.edu>
.PP
.SH SEE ALSO
See project page at <https://edryd.org/projects/tisp.html>
.PP
View source code at <https://git.edryd.org/tisp>
.PP
.SH LICENSE
zlib License
