.\" x-roff document
.do mso man.tmac
.TH tisp 1 "February 2018" "tisp 0.0.0"
.PP
.SH NAME
tisp - tiny lisp
.PP
.SH SYNOPSIS
\fBtisp\fP [\fB-hv\fP] [\fICODE\fP] 
.PP
.SH DESCRIPTION
Tiny lisp implementation, still in heavy development, barely even "useable." Designed to be scheme-like, ie very minimalist.
.PP
.SH OPTIONS
.TP
\fB-h
\fRPrint help and exit
.PP
.TP
\fB-v
\fRPrint version info and exit
.PP
.SH USAGE
Run the program from the command line to launch the REPL, type command and press enter to see result. Alternatively you can pass a single command as the first argument to the command line program and see a result instantly.
.PP
.SH AUTHOR
Ed van Bruggen <ed@edryd.org>
.PP
.SH SEE ALSO
See project page at <https://edryd.org/projects/tisp.html>
.PP
View source code at <https://github.com/edvb/tisp>
.PP
.SH LICENSE
zlib License
