.TH TISP 1 "March 2021" "tisp 0.0.0" 
.PP
.SH NAME
tisp \- tiny lisp
.PP
.SH SYNOPSIS
tisp [-hv] [-c COMMAND] [-] [FILE ...]
.PP
.SH DESCRIPTION
.PP
Tisp programming language interpreter.  Read and evaluate all files in order given, if file name is '-' read from 'stdin'. If no files are supplied launch REPL.
.PP
.SH OPTIONS
.TP
\fB-c COMMAND\fP
Read \fICOMMAND\fP as a line of Tisp code and print result
.PP
.TP
\fB-h\fP
Print help and exit
.PP
.TP
\fB-v\fP
Print version info and exit
.PP
.SH USAGE
.PP
Run the program from the command line to type a single command and press enter to see the result.
.PP
.RS 4
.EX

$ tisp
> (cons 1 2)
(1 . 2)

.EE
.RE
Alternatively you can pass a file name which will be opened and run, outputting the result before exiting.
.PP
.RS 4
.EX

$ echo '((lambda (x) (+ x 1)) 10)' > inc.tsp
$ tisp inc.tsp
11

.EE
.RE
Commands can also be piped directing into Tisp through the command line.
.PP
.RS 4
.EX

$ echo '(= "foo" "foo")' | tisp
t

.EE
.RE
Or given directly to Tisp as an argument:
.PP
.RS 4
.EX

$ tisp -c "(reverse '(1/2 1/4 1/8 1/16))"
(1/16 1/8 1/4 1/2)

.EE
.RE
.SH AUTHOR
.PP
Ed van Bruggen <ed@edryd.org>
.PP
.SH SEE ALSO
.PP
tisp(7) tsp(1)
.PP
See project at <https://edryd.org/projects/tisp>
.PP
View source code at <https://git.edryd.org/tisp>
.PP
.SH LICENSE
.PP
zlib License 
.PP

