#!/usr/bin/env bash

total=0
pass=0

export LD_LIBRARY_PATH="$PWD/../tib:$LD_LIBRARY_PATH"

for file in */*.tsp; do
	expect=${file%.tsp}.expect

	echo -n "testing $file ... "
	if [[ $(../tisp "$file" 2>&1 | diff -q "$expect" - 2>&1 ) ]]; then
		echo fail
	else
		echo ok
		((pass++))
	fi
	((total++))
done

echo "$pass/$total tests passed"

[[ $pass == $total ]] && exit 0
exit 1
